# Generated by Django 4.1.7 on 2023-02-28 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('area_delivery_charges', models.IntegerField()),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('idcity', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('idoffer', models.AutoField(primary_key=True, serialize=False)),
                ('offer_value', models.DecimalField(decimal_places=0, max_digits=2)),
                ('offer_start_date', models.DateField()),
                ('offer_end_date', models.DateField()),
                ('offer_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'offer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.AutoField(primary_key=True, serialize=False)),
                ('orderfname', models.CharField(max_length=150, null=True)),
                ('orderlname', models.CharField(max_length=150, null=True)),
                ('orderemail', models.CharField(max_length=150, null=True)),
                ('ordermobile', models.CharField(max_length=150, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('cancel_order_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivery_date', models.DateTimeField(auto_now_add=True)),
                ('order_delivery_address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('total_amount', models.FloatField()),
                ('order_payment_method', models.CharField(max_length=150)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('order_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Pending', max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('is_cancel_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('area_pincode', models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.area')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('offer_price', models.FloatField(default=0)),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand')),
                ('offer_idoffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.offer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('idsalon', models.AutoField(primary_key=True, serialize=False)),
                ('salon_name', models.CharField(max_length=45)),
                ('salon_email', models.CharField(max_length=45)),
                ('salon_phone', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('salon_description', models.CharField(max_length=200)),
                ('salon_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('salon_address', models.CharField(max_length=500, null=True)),
                ('area_pincode', models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.area')),
            ],
            options={
                'db_table': 'salon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=25, null=True)),
                ('user_last_name', models.CharField(max_length=25, null=True)),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_password', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=245, unique=True)),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
                ('user_address', models.TextField(max_length=200, null=True)),
                ('user_sec_question', models.CharField(max_length=60, null=True)),
                ('user_sec_answer', models.CharField(max_length=60, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='userimages')),
                ('is_admin', models.IntegerField(default=0)),
                ('forgot_password_token', models.CharField(default='', max_length=100)),
                ('idsalon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.salon')),
                ('pincode', models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.area')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idreview', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review_description', models.TextField(blank=True, max_length=500)),
                ('rating_value', models.FloatField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('reviewDate', models.DateField(null=True, verbose_name=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_idproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('user_iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('psubimage', models.ImageField(upload_to='psubcatImage')),
                ('pcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='psubcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productsubcategory'),
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order_idorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('product_idProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
            options={
                'db_table': 'ordered_product',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_iduser',
            field=models.ForeignKey(db_column='user_iduser', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('offer_record', models.IntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city'),
        ),
    ]
